/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        moss: {
          50: 'var(--moss-50)',
          100: 'var(--moss-100)',
          200: 'var(--moss-200)',
          300: 'var(--moss-300)',
          400: 'var(--moss-400)',
          500: 'var(--moss-500)',
          600: 'var(--moss-600)',
          700: 'var(--moss-700)',
          800: 'var(--moss-800)',
          900: 'var(--moss-900)',
        },
        amber: {
          50: 'var(--amber-50)',
          100: 'var(--amber-100)',
          300: 'var(--amber-300)',
          500: 'var(--amber-500)',
          700: 'var(--amber-700)',
          900: 'var(--amber-900)',
        },
        stone: {
          50: 'var(--stone-50)',
          100: 'var(--stone-100)',
          200: 'var(--stone-200)',
          300: 'var(--stone-300)',
          500: 'var(--stone-500)',
          700: 'var(--stone-700)',
          900: 'var(--stone-900)',
        },
        cream: 'var(--cream)',
        parchment: 'var(--parchment)',
        difficulty: {
          easy: 'var(--difficulty-easy)',
          medium: 'var(--difficulty-medium)',
          hard: 'var(--difficulty-hard)',
        },
        status: {
          completed: 'var(--status-completed)',
          inprogress: 'var(--status-inprogress)',
          new: 'var(--status-new)',
        },
        dark: {
          bg: 'var(--dark-bg)',
          surface: 'var(--dark-surface)',
          border: 'var(--dark-border)',
          text: 'var(--dark-text)',
          muted: 'var(--dark-muted)',
        },
      },
      fontFamily: {
        playfair: ['"Playfair Display"', 'Georgia', 'serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
        jetbrains: ['"JetBrains Mono"', 'monospace'],
        crimson: ['"Crimson Pro"', 'Georgia', 'serif'],
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
        card: '12px',
        button: '8px',
        modal: '16px',
        pill: '9999px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        sm: '0 1px 2px rgba(0,0,0,0.05)',
        md: '0 4px 12px rgba(0,0,0,0.08)',
        lg: '0 8px 30px rgba(0,0,0,0.12)',
        glow: '0 0 40px rgba(106,155,106,0.15)',
      },
      transitionTimingFunction: {
        'breathe': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'drift': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
        'appear': 'cubic-bezier(0, 0, 0.2, 1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "leaf-drift": {
          "0%, 100%": { transform: "translateX(0px)" },
          "50%": { transform: "translateX(10px)" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "0" },
          "50%": { opacity: "0.3" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "leaf-drift": "leaf-drift 8s ease-in-out infinite",
        "glow-pulse": "glow-pulse 3s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}